### ISSUE TITLE
Original Doom controls don't work

### ISSUE THREAD

**Issue by BlackJar72** [AXDOOMER/mochadoom#3]
I don't know if you're still working on this, but the original controls don't work -- its not nostalgia, I find that Doom engine games are just easier to play using the control scheme they were designed for, so old and new (for new comers) should both be supported.

If you're not still planning on working on this sorry to have bothered you.

**Comment by AXDOOMER** [comment]
Check out this fork (he might have fixed this problem): https://github.com/jendave/mochadoom
Else another guy may also work on this project on his side: https://github.com/PaperTanuki/mochadoom

On my part, I don't have time to work on this and I have lost interest for now. There a a lot of forks since I have put it on GitHub, the source port is slowly progressing in each of them.

**Comment by AXDOOMER** [comment]
Have you tried using your own `default.cfg` that you use with the original executable?

**Comment by BlackJar72** [comment]
Thanks.

**Comment by AXDOOMER** [comment]
These are the classic controls, the defaults under vanilla Doom that moves you with the arrows.
```
key_right		235
key_left		233
key_up			230
key_down		238
key_strafeleft		44
key_straferight		46
key_fire		157
key_use			32
key_strafe		184
key_speed		182
```
The keys `,` and `.` are also set for strafing. To find the codes for the keys that represent a characeters, check the under the HTML column in this table: http://www.asciitable.com/
If they are special keys, you need to check the arbitrary codes that are assigned to them in `/src/g/Keys.java` in the source code.
