### ISSUE TITLE
Mouse grabbing

### ISSUE THREAD

**Issue by AXDOOMER** [AXDOOMER/mochadoom#9]
When the game is paused, a demo is playing or the player is in the menus, the mouse should be ungrabbed to let the player do other things. (Just like Chocolate-Doom)

**Comment by GoodSign2017** [comment]
Should be resolved as of now. I've added the function to LAlt key. You press it, and the mouse is free, but you cannot select menus with mouse. You press it again, and it is grabbed back. Or you can click.

**Comment by AXDOOMER** [comment]
Can you make it so it's always ungrabbed when a demo is playing, when the menu is open or when the pause is activated? This way the ungrab key wouldn't be necessary.

**Comment by GoodSign2017** [comment]
I think it is a part of user preference. Also, making always ungrabbed in menu will break ability to select menu items with mouse.

**Comment by AXDOOMER** [comment]
It could be made so the window captures the cursor's location even if it's ungrabbed. If you'd move your mouse cursor above a menu item, then the game's skull cursor would move beside that item.

**Comment by GoodSign2017** [comment]
At first, I've tried this approach. It was too buggy. And the mouse behavior that way is far from vanilla and unobvious to user.

**Comment by GoodSign2017** [comment]
You can checkout how it was in 77de67f

**Comment by AXDOOMER** [comment]
> At first, I've tried this approach. It was too buggy. And the mouse behavior that way is far from vanilla and unobvious to user.

ZDoom uses that kind of approach and it works fine. Vanilla didn't had a windowed mode, so changing the mouse behavior in windowed mode is not a problem.

**Comment by GoodSign2017** [comment]
ZDoom is much further from vanilla to start with. And it breaks vanilla menu navigation with mouse at all by default - even in fullscreen. And it introduces its own cursor theme.

Chocolate Doom does not break, and does not add own mouse cursor - but you cant just click on item with mouse, when it is ungrabbed. It is not ideal, there are limitations of SDL library which I know about because I have developed under SDL some time ago. But it was reference for me.

I didn't made it ideal, yes. But I think, I've made It a little bit better, maybe there are still a few bugs, but at least it is possible to fix them, and there is no such limitations, as on SDL. And I feel that if I start to touch it again, it will either stop working DOOM way, or start bugging my way a lot.

Maybe, I will return to that in some time, but definitely now I would not be trying to make it possible to follow uncaptured mouse movements in menu properly. It needs totally new logic. Now I will only fix bugs with mouse capture.

However, making it always uncaptured when paused or playing demo should not be very hard to implement. I'll think about it.

**Comment by AXDOOMER** [comment]
I don't think we need to add our own cursor. The system's mouse cursor is good enough. 

Also, if we make it like ZDoom so people can click on the different menu items, then it will be more intuitive for players who use touch screens. The current approach where you need to move the mouse up and down to slide from item to item is difficult. 

The current approach is still very good though, I just believe it could be ideal if we can get rid of the mouse grab/ungrab key.

**Comment by GoodSign2017** [comment]
Then the touchscreen mode should be very separate and optional, and thoughts in that direction should be about something like developing touch-match matrix for determination of where touched screen means what item. Just no need to start this development from breaking mouse.

**Comment by AXDOOMER** [comment]
Mouse grabbing works. The player must press `ALT` (the left one) when the game is paused to release the mouse.
